// config/spells.js
// All spells deal fixed damage (dmg) and cost MP.
const spellsConfig = [
    { name:'Magic Missile',   cost:5,  dmg:8,  levelReq:1,  desc:'Bolt of force.' },
    { name:'Firebolt',        cost:6,  dmg:12, levelReq:2, desc:'Small ball of fire.' },
    { name:'Ice Lance',       cost:7,  dmg:14, levelReq:3, desc:'Shard of ice.' },
    { name:'Arcane Blast',    cost:8,  dmg:16, levelReq:4, desc:'Raw magical energy.' },
    { name:'Lightning Spark', cost:9,  dmg:18, levelReq:5, desc:'Crack of lightning.' },
    { name:'Shadow Bolt',     cost:10, dmg:20, levelReq:6, desc:'Dark energy.' },
    { name:'Flame Wave',      cost:12, dmg:24, levelReq:7, desc:'Wave of fire.' },
    { name:'Frost Nova',      cost:12, dmg:22, levelReq:7, desc:'Icy explosion.' },
    { name:'Meteor Shower',   cost:15, dmg:30, levelReq:8, desc:'Raining meteors.' },
    { name:'Thunder Strike',  cost:15, dmg:32, levelReq:8, desc:'Powerful bolt.' },
    { name:'Soul Rend',       cost:16, dmg:34, levelReq:9, desc:'Tears at soul.' },
    { name:'Blizzard',        cost:18, dmg:36, levelReq:9, desc:'Hail storm.' },
    { name:'Inferno',         cost:20, dmg:40, levelReq:10,desc:'Engulfs in flames.' },
    { name:'Chain Lightning', cost:20, dmg:38, levelReq:10,desc:'Jumps targets.' },
    { name:'Ethereal Barrage',cost:22, dmg:42, levelReq:11,desc:'Spiritual bolts.' },
    { name:'Volcanic Eruption',cost:24,dmg:44, levelReq:11,desc:'Burst of lava.' },
    { name:'Stormcaller',     cost:25, dmg:46, levelReq:12,desc:'Wrath of storms.' },
    { name:'Crystal Shards',  cost:26, dmg:48, levelReq:12,desc:'Sharp crystals.' },
    { name:'Arcane Cataclysm',cost:28, dmg:50, levelReq:13,desc:'Massive surge.' },
    { name:'Paralyzing Bolt', cost:18, dmg:20, levelReq:9, desc:'Electric stun.' },
    { name:'Wind Cutter',     cost:10, dmg:15, levelReq:4, desc:'Razor wind.' },
    { name:'Earth Spike',     cost:12, dmg:18, levelReq:5, desc:'Ground spikes.' },
    { name:'Solar Flare',     cost:22, dmg:45, levelReq:11,desc:'Solar burst.' },
    { name:'Lunar Beam',      cost:20, dmg:42, levelReq:10,desc:'Moonlight.' },
    { name:'Bone Spear',      cost:14, dmg:22, levelReq:6, desc:'Spectral bone.' },
    { name:'Venom Nova',      cost:16, dmg:24, levelReq:7, desc:'Toxic gas.' },
    { name:'Chaos Bolt',      cost:30, dmg:55, levelReq:14,desc:'Unstable energy.' },
    { name:'Divine Smite',    cost:18, dmg:38, levelReq:10,desc:'Holy energy.' },
    { name:'Plague Swarm',    cost:20, dmg:40, levelReq:11,desc:'Diseased insects.' },
    { name:'Soul Fire',       cost:24, dmg:48, levelReq:12,desc:'Burns spirit.' },
    { name:'Frostbite',       cost:14, dmg:22, levelReq:6, desc:'Chilling attack.' },
    { name:'Hellfire',        cost:26, dmg:52, levelReq:13,desc:'Underworld fire.' },
    { name:'Thunder Clap',    cost:12, dmg:20, levelReq:5, desc:'Thunder shock.' },
    { name:'Shadowflame',     cost:28, dmg:54, levelReq:14,desc:'Dark fire.' },
    { name:'Abyssal Grasp',   cost:30, dmg:56, levelReq:15,desc:'Void tendrils.' },
    { name:'Radiant Beam',    cost:22, dmg:44, levelReq:11,desc:'Pure light.' },
    { name:'Magnet Storm',    cost:18, dmg:36, levelReq:10,desc:'Metal shards.' },
    { name:'Spirit Bomb',     cost:35, dmg:60, levelReq:16,desc:'Energy bomb.' },
    { name:'Blade Storm',     cost:20, dmg:42, levelReq:10,desc:'Whirling blades.' },
    { name:'Tsunami',         cost:28, dmg:50, levelReq:13,desc:'Wall of water.' },
    { name:'Phoenix Flame',   cost:32, dmg:58, levelReq:15,desc:'Rebirth fire.' },
    { name:'Galactic Nova',   cost:40, dmg:70, levelReq:17,desc:'Cosmic blast.' },
    { name:'Null Zone',       cost:26, dmg:46, levelReq:12,desc:'Void damage.' },
    { name:'Temporal Rift',   cost:34, dmg:64, levelReq:16,desc:'Time slice.' },
    { name:'Essence Drain',   cost:22, dmg:40, levelReq:10,desc:'Saps life.' },
    { name:'Ocean’s Roar',    cost:24, dmg:48, levelReq:11,desc:'Sea surge.' },
    { name:'Meteor Impact',   cost:36, dmg:72, levelReq:18,desc:'Massive meteor.' },
    { name:'Void Eruption',   cost:38, dmg:74, levelReq:19,desc:'Void chaos.' },
    { name:'Starlight Strike',cost:30, dmg:60, levelReq:17,desc:'Star energy.' }
  ];
  